setwd("E:/Python/Data Science R/Lecture4")
getwd()
mydata3=read.csv("Golfball.csv", header=TRUE)
View(mydata3)
attach(mydata3)
mydata
library(psych)
describeBy(Distance,group=Design)
library(lattice)
histogram(~Distance|Design)
boxplot(Distance~Design,horizontal=TRUE,col=c("Red","Blue","Orange","Pink"))
Model=aov(Distance~Design,data=mydata)
summary(Model)
print(summary(Model), digits = 6)
TukeyHSD(Model)
TukeyHSD(Model, confidence=0.99)